
<div class="container-fluid">
    <section class="container">

        <form action="" method="post">
        <div class="container-page">
            <div class="col-md-6">
                <h3 class="dark-grey">Регистрация</h3>
                <div class="form-group col-lg-7">
                    <label>Логин</label>
                    <input type="text" name="login" class="form-control" id="" value="" required>
                </div>
                <div class="form-group col-lg-4">

                </div>
                <div class="form-group col-lg-7">
                    <label>Ваше Имя</label>
                    <input type="text" name="name" class="form-control" id="" value="" required>
                </div>

                <div class="form-group col-lg-4">
                    <label>Пол</label>
                    <select name="sex" class="form-control"  >
                        <option> Mужчина
                        <option> Женщина
                    </select>

                </div>
                <div class="form-group col-lg-7">
                    <label>Ваша Фамилия</label>
                    <input type="text" name="secondname" class="form-control" id="" value=""  >
                </div>
                <div class="form-group col-lg-7">
                    <label>Пароль</label>
                    <input type="password" name="password1" class="form-control" id="" value="" required>
                    <label>Повторите пароль</label>
                    <input type="password" name="password2" class="form-control" id="" value="" required>
                </div>

                <div class="form-group col-lg-7">
                    <label>E-mail адрес</label>
                    <input type="email" name="email" class="form-control" id="" value="" required>
                </div>

            </div>

            <div class="col-md-5">
                <h3 class="dark-grey">Правила заполнения</h3>
                <p>
                   Обязательно заполните все поля!
                </p>
                <p>
                    Пароли должны совпадать!
                </p>
                <p>
                    Email должен быть достоверным
                </p>

                <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
            </div>
        </div>
        </form>
    </section>
</div>