<div class="container">
	<div id="loginbox" style="9" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
		<div class="panel panel-info" >
			<div class="panel-heading">
				<div class="panel-title">Вход в систему</div>
				<div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="#">Забыли пароль?</a></div>
			</div>
			<div style="padding-top:30px" class="panel-body" >

				<div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>

				<form id="loginform" class="form-horizontal" role="form" action="" method="post">

					<div style="margin-bottom: 25px" class="input-group">
						<span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
						<input id="login-username" type="text" class="form-control" name="username"  value="<?=$_POST["username"]?>" placeholder="Логин или E-mail">
					</div>

					<div style="margin-bottom: 25px" class="input-group">
						<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
						<input id="login-password" type="password" class="form-control" name="password" value="<?=$_POST["password"]?>"  placeholder="пароль">
					</div>

					<?php if($this->message) {?>
						<div style="margin-bottom: 25px" class="input-group">
							<b style="color: red"><?= $this->message ?></b>
						</div>
					<?php } ?>

					<div style="margin-top:10px" class="form-group">
						<div class="col-sm-6 controls">
                            <button type="submit" class="btn btn-primary">Вход</button>
						</div>
					</div>
                    </form>
					<div class="form-group">
						<div class="col-md-12 control">
							<div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
								Вы еще не зарегистрированы?
								<a href="?go=register">Регистрация</a>
							</div>
						</div>
					</div>


			</div>
		</div>
	</div>

</div>
    