<html>
<head>
    <title>
        Регистрация
    </title>
    <link rel="stylesheet" href="main.css">
</head>
<body>
<div class="add">
    <h1>Регистрация</h1>
    <form method="post">
        <input type="text" name="login">  Логин</br></br>
        <input type="password" name="password">   Пароль</br></br>
        <input type="text" name="fullname">   Полное Имя</br></br>
        <input type="submit" value="Подтевердить"></br>
    </form>
</div>
</body>
</html>