<div class="container">
        <h1>Добавление книг</h1>
        <hr>
        <div class="row">
            <!-- left column -->
            <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data"   >
                <div class="col-md-3">
                    <div class="text-center">
                        <img src="View/image/book_2.png" class="igorpage"   alt="avatar">
                        <h6>Загрузить изображение...</h6>
                       <span class="btn btn-default btn-file">
                              Загрузить <input type="file" name="pictures[]"  >
                        </span>
                    </div>
                </div>

            <!-- edit form column -->
            <div class="col-md-5 personal-info">
                <!-- Будет выходить ошибка если в форме лишняя информация -->
                <?php if($eror) echo '
                <div class="alert alert-info alert-dismissable">
                    <a class="panel-close close" data-dismiss="alert">×</a>
                    <i class="fa fa-coffee"> </i>
                    This is an <strong>.alert</strong>. Use this to show important messages to the user.
                </div>';
                ?>
                <h3>Информация</h3>

                    <div class="form-group">
                        <label class="col-lg-3 control-label">Название:</label>
                        <div class="col-lg-8">
                            <input class="form-control" type="text" name="name" value="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label">Автор:</label>
                        <div class="col-lg-8">
                            <input class="form-control" type="text" name="author" value="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label">Жанр:</label>
                        <div class="col-lg-8">
                            <input class="form-control" type="text" name="ganre" value="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Год:</label>
                        <div class="col-md-8">
                            <input class="form-control" type="text" name="year" value="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label"></label>
                        <div class="col-md-8">
                            <input type="submit" class="btn btn-primary" value="Сохранить">
                            <input type="reset" class="btn btn-default" value="Отмена">
                        </div>
                    </div>
                </form>
            </div>
        </div>
</div>
